packages: []

catalogs:
  build:
    '@vitejs/plugin-vue': ^5.2.4
    jsdom: ^26.1.0
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@primevue/auto-import-resolver': ^4.4.1
    '@types/node': ^22.15.31
    '@vue-macros/volar': ^3.0.0-beta.14
    '@vue/test-utils': ^2.4.6
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-tailwindcss: 4.0.0-beta.0
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.3
    vue-tsc: ^2.2.10
  frontend:
    '@fontsource/inter': ^5.2.8
    '@primeuix/themes': ^1.2.5
    '@tailwindcss/vite': ^4.1.16
    '@vueuse/core': ^13.3.0
    date-fns: ^4.1.0
    dompurify: ^3.3.0

    jsondiffpatch: ^0.7.3
    microdiff: ^1.5.0
    primeicons: ^7.0.0
    primevue: ^4.4.1
    tailwindcss: ^4.1.16
    tailwindcss-primeui: ^0.6.1
    uuid: ^13.0.0
    vue: ^3.5.16
    vue-router: ^4.5.1
    zod: ^4.1.12
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
