packages: []

catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.2
    jsdom: ^27.2.0
    unplugin: ^2.3.11
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.17.1
    vite: ^7.2.4
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@primevue/auto-import-resolver': ^4.4.1
    '@types/node': ^22.19.1
    '@vue-macros/volar': ^3.1.1
    '@vue/test-utils': ^2.4.6
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    eslint-plugin-tailwindcss: 4.0.0-beta.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    taze: ^19.9.0
    typescript: ^5.9.3
    vitest: ^4.0.13
    vue-tsc: ^3.1.5
  frontend:
    '@fontsource/inter': ^5.2.8
    '@primeuix/themes': ^1.2.5
    '@tailwindcss/vite': ^4.1.17
    '@vueuse/core': ^14.0.0
    date-fns: ^4.1.0
    dompurify: ^3.3.0

    jsondiffpatch: ^0.7.3
    primeicons: ^7.0.0
    primevue: ^4.4.1
    tailwindcss: ^4.1.17
    tailwindcss-primeui: ^0.6.1
    uuid: ^13.0.0
    vue: ^3.5.24
    vue-router: ^4.6.3
    zod: ^4.1.12
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
